"""Public model surface — every request and response shape exposed by the SDK.

Import via ``voicetel.models.<Name>`` or directly from the package: every model is re-exported
at the top level so ``from voicetel.models import NumberAddRequest`` works.

Naming follows the OpenAPI spec exactly, PascalCased — so ``numberAddRequest`` in the spec
becomes :class:`NumberAddRequest` here. Response *data* shapes are named after their schema
(``NumberAddData``, ``AccountData``, etc.). The ``{status: 'success', data: <T>}`` envelope is
stripped by the transport before the data shape is parsed, so callers always work with the
inner type directly.
"""

from __future__ import annotations

from ._base import PhoneNumber
from .account import (
    AccountAddData,
    AccountAddRequest,
    AccountApiKeyData,
    AccountCdrData,
    AccountCreditsData,
    AccountData,
    AccountMrcData,
    AccountPaymentsData,
    AccountPutData,
    AccountPutRequest,
    AccountRates,
    AccountRecoverData,
    AccountRecoverRequest,
    AccountRegistrationData,
    AccountServices,
    AccountSignupData,
    AccountSignupRequest,
    ApiKeyRequest,
    CdrEntry,
    CdrEntryValue,
    CreditEntry,
    MrcCharge,
    PaymentEntry,
    PaymentStatus,
)
from .acl import (
    AclAddData,
    AclConflictData,
    AclFailedEntry,
    AclFailureReason,
    AclListData,
    AclModifyRequest,
    AclRemoveData,
)
from .authentication import (
    AuthGetData,
    AuthPutConflictData,
    AuthPutData,
    AuthPutRequest,
    AuthType,
    AuthUpdatedEntry,
    AuthUpdatedField,
)
from .common import CidrEntry, ErrorResponse
from .e911 import (
    E911AddressRequest,
    E911AllData,
    E911CreateRequest,
    E911Entry,
    E911ProvisionByIdRequest,
    E911RecordData,
    E911ValidatedAddress,
    E911ValidateData,
)
from .gateways import (
    GatewayAddRequest,
    GatewayEntry,
    GatewayNumbersData,
    GatewayNumberSummary,
    GatewaysListData,
    GatewayUpdateRequest,
)
from .inumbering import (
    InventoryCoverageData,
    InventoryCoverageItem,
    InventoryItem,
    InventorySearchData,
    NameType,
    OrderCreateData,
    OrderCreateRequest,
    OrderFailedEntry,
    OrderNumberSpec,
    PortAvailabilityData,
    PortDetail,
    PortDetailData,
    PortFeature,
    PortFeatureLidb,
    PortFeatureRouting,
    PortFeatureSms,
    PortListData,
    PortSubmitData,
    PortSubmitRequest,
    PortSummary,
    StreetDirection,
)
from .lookups import CnamData, LrnData, LrnLookupData
from .messaging import (
    BrandRegistrationResult,
    CampaignRegistrationResult,
    CampaignStatusItem,
    MessageDirection,
    MessageHistoryData,
    MessageHistoryType,
    MessageRecord,
    MessageRecordValue,
    MessageSendData,
    MessageSendRequest,
    MessageType,
    MessagingBrandCreateData,
    MessagingBrandCreateRequest,
    MessagingCampaignCreateData,
    MessagingCampaignCreateRequest,
    MessagingCampaignStatusData,
)
from .numbers import (
    CampaignBinding,
    CampaignUnassignFailure,
    MessagingNetwork,
    NumberAddData,
    NumberAddRequest,
    NumberCampaignAssignRequest,
    NumberCnamData,
    NumberCnamRequest,
    NumberDetail,
    NumberFaxData,
    NumberFaxRequest,
    NumberForwardData,
    NumberForwardRequest,
    NumberLidbData,
    NumberLidbRequest,
    NumberMessagingCampaignAssignData,
    NumberMessagingCampaignUnassignData,
    NumberMessagingPatchData,
    NumberMessagingPatchField,
    NumberMessagingPatchRequest,
    NumberMessagingState,
    NumberMoveData,
    NumberMoveRequest,
    NumberRouteData,
    NumberRouteRequest,
    NumbersListData,
    NumbersMessagingCampaignUnassignData,
    NumbersMessagingListData,
    NumberSmsData,
    NumberSmsRequest,
    NumberTranslationData,
    NumberTranslationRequest,
    PortOutPinUpdateData,
    PortOutPinUpdateRequest,
    PreviousNetwork,
    SmsRouteType,
)
from .support import (
    ConversationEmbedded,
    CustomerAddress,
    CustomerContactEntry,
    CustomerEmbedded,
    CustomerWebsiteEntry,
    CustomFieldValue,
    SupportAttachment,
    SupportConversation,
    SupportCustomer,
    SupportThread,
    ThreadEmbedded,
    TicketAction,
    TicketActor,
    TicketCreateRequest,
    TicketData,
    TicketReplyData,
    TicketReplyRequest,
    TicketsListData,
    TicketSource,
    TicketStatus,
    TicketThreadsData,
    TicketUpdateData,
    TicketUpdateRequest,
)

__all__ = [
    # account
    "AccountAddData",
    "AccountAddRequest",
    "AccountApiKeyData",
    "AccountCdrData",
    "AccountCreditsData",
    "AccountData",
    "AccountMrcData",
    "AccountPaymentsData",
    "AccountPutData",
    "AccountPutRequest",
    "AccountRates",
    "AccountRecoverData",
    "AccountRecoverRequest",
    "AccountRegistrationData",
    "AccountServices",
    "AccountSignupData",
    "AccountSignupRequest",
    # acl
    "AclAddData",
    "AclConflictData",
    "AclFailedEntry",
    "AclFailureReason",
    "AclListData",
    "AclModifyRequest",
    "AclRemoveData",
    "ApiKeyRequest",
    # authentication
    "AuthGetData",
    "AuthPutConflictData",
    "AuthPutData",
    "AuthPutRequest",
    "AuthType",
    "AuthUpdatedEntry",
    "AuthUpdatedField",
    # messaging
    "BrandRegistrationResult",
    # numbers
    "CampaignBinding",
    "CampaignRegistrationResult",
    "CampaignStatusItem",
    "CampaignUnassignFailure",
    "CdrEntry",
    "CdrEntryValue",
    # common
    "CidrEntry",
    # lookups
    "CnamData",
    # support
    "ConversationEmbedded",
    "CreditEntry",
    "CustomFieldValue",
    "CustomerAddress",
    "CustomerContactEntry",
    "CustomerEmbedded",
    "CustomerWebsiteEntry",
    # e911
    "E911AddressRequest",
    "E911AllData",
    "E911CreateRequest",
    "E911Entry",
    "E911ProvisionByIdRequest",
    "E911RecordData",
    "E911ValidateData",
    "E911ValidatedAddress",
    "ErrorResponse",
    # gateways
    "GatewayAddRequest",
    "GatewayEntry",
    "GatewayNumberSummary",
    "GatewayNumbersData",
    "GatewayUpdateRequest",
    "GatewaysListData",
    # inumbering
    "InventoryCoverageData",
    "InventoryCoverageItem",
    "InventoryItem",
    "InventorySearchData",
    "LrnData",
    "LrnLookupData",
    "MessageDirection",
    "MessageHistoryData",
    "MessageHistoryType",
    "MessageRecord",
    "MessageRecordValue",
    "MessageSendData",
    "MessageSendRequest",
    "MessageType",
    "MessagingBrandCreateData",
    "MessagingBrandCreateRequest",
    "MessagingCampaignCreateData",
    "MessagingCampaignCreateRequest",
    "MessagingCampaignStatusData",
    "MessagingNetwork",
    "MrcCharge",
    "NameType",
    "NumberAddData",
    "NumberAddRequest",
    "NumberCampaignAssignRequest",
    "NumberCnamData",
    "NumberCnamRequest",
    "NumberDetail",
    "NumberFaxData",
    "NumberFaxRequest",
    "NumberForwardData",
    "NumberForwardRequest",
    "NumberLidbData",
    "NumberLidbRequest",
    "NumberMessagingCampaignAssignData",
    "NumberMessagingCampaignUnassignData",
    "NumberMessagingPatchData",
    "NumberMessagingPatchField",
    "NumberMessagingPatchRequest",
    "NumberMessagingState",
    "NumberMoveData",
    "NumberMoveRequest",
    "NumberRouteData",
    "NumberRouteRequest",
    "NumberSmsData",
    "NumberSmsRequest",
    "NumberTranslationData",
    "NumberTranslationRequest",
    "NumbersListData",
    "NumbersMessagingCampaignUnassignData",
    "NumbersMessagingListData",
    "OrderCreateData",
    "OrderCreateRequest",
    "OrderFailedEntry",
    "OrderNumberSpec",
    "PaymentEntry",
    "PaymentStatus",
    # base
    "PhoneNumber",
    "PortAvailabilityData",
    "PortDetail",
    "PortDetailData",
    "PortFeature",
    "PortFeatureLidb",
    "PortFeatureRouting",
    "PortFeatureSms",
    "PortListData",
    "PortOutPinUpdateData",
    "PortOutPinUpdateRequest",
    "PortSubmitData",
    "PortSubmitRequest",
    "PortSummary",
    "PreviousNetwork",
    "SmsRouteType",
    "StreetDirection",
    "SupportAttachment",
    "SupportConversation",
    "SupportCustomer",
    "SupportThread",
    "ThreadEmbedded",
    "TicketAction",
    "TicketActor",
    "TicketCreateRequest",
    "TicketData",
    "TicketReplyData",
    "TicketReplyRequest",
    "TicketSource",
    "TicketStatus",
    "TicketThreadsData",
    "TicketUpdateData",
    "TicketUpdateRequest",
    "TicketsListData",
]
